---
title: "Data Prep"
format: html
editor: visual
---

```{r}
library(haven)
library(tidyverse)
library(feather)
library(psych)
library(ggcorrplot)
library(viridis)
library(jtools)
library(lavaan)
library(broom)
library(huxtable)
library(purrr)
```

```{r}
german_df <- read_sav("../data/Compassion-DE_19 November 2023_19.42.sav")
```

```{r}
german_df

```

```{r}
filtered_german_df <- german_df %>% 
  filter(SOCS_O_10 == 4) %>% 
  filter(CEAS_TO1_4 == 10)

filtered_german_df

```

```{r}
socs_o_df <- filtered_german_df %>% 
  select(ResponseId, starts_with("SOCS_O")) %>% 
  mutate(across(starts_with("SOCS"), as.numeric)) %>% 
  pivot_longer(-ResponseId, names_to = "item", values_to = "response") %>% 
  filter(item != "SOCS_O_10") %>% 
  mutate(item_number = if_else(as.numeric(str_extract(item, "\\d+")) > 10 & str_detect(item, "SOCS_O"), as.numeric(str_extract(item, "\\d+")) - 1, as.numeric(str_extract(item, "\\d+")))) %>% 
  mutate(item = if_else(str_detect(item, "SOCS_O"), str_c("SOCS-O_", item_number), item)) %>% 
  select(-item_number) %>% 
  group_by(ResponseId) %>% 
  filter(!any(is.na(response))) %>% 
  ungroup() %>% 
  mutate(item = str_replace(item, "-", "_")) %>% 
  mutate(sub_scale = case_when(
    item %in% c("SOCS_O_1", "SOCS_O_6", "SOCS_O_11", "SOCS_O_16") ~ "SOCS_O_Recognizing_Suffering",
    item %in% c("SOCS_O_2", "SOCS_O_7", "SOCS_O_12", "SOCS_O_17") ~ "SOCS_O_Understanding_Suffering",
    item %in% c("SOCS_O_3", "SOCS_O_8", "SOCS_O_13", "SOCS_O_18") ~ "SOCS_O_Feeling_Suffering",
    item %in% c("SOCS_O_4", "SOCS_O_9", "SOCS_O_14", "SOCS_O_19") ~ "SOCS_O_Tolerating_Feelings",
    item %in% c("SOCS_O_5", "SOCS_O_10", "SOCS_O_15", "SOCS_O_20") ~ "SOCS_O_Acting_To_Alleviate"
  ))

```

```{r}
socs_o_df %>% 
  write_feather("../results/socs_o_tidy.feather")

```

## SOCS-S

```{r}
socs_s_df <- filtered_german_df %>% 
  select(ResponseId, starts_with("SOCS_S")) %>% 
  mutate(across(starts_with("SOCS"), as.numeric)) %>% 
  pivot_longer(-ResponseId, names_to = "item", values_to = "response") %>% 
  group_by(ResponseId) %>%
  filter(!any(is.na(response))) %>%
  ungroup() %>% 
  mutate(sub_scale = case_when(
    item %in% c("SOCS_S_1", "SOCS_S_6", "SOCS_S_11", "SOCS_S_16") ~ "SOCS_S_Recognizing_Suffering",
    item %in% c("SOCS_S_2", "SOCS_S_7", "SOCS_S_12", "SOCS_S_17") ~ "SOCS_S_Understanding_Suffering",
    item %in% c("SOCS_S_3", "SOCS_S_8", "SOCS_S_13", "SOCS_S_18") ~ "SOCS_S_Feeling_Suffering",
    item %in% c("SOCS_S_4", "SOCS_S_9", "SOCS_S_14", "SOCS_S_19") ~ "SOCS_S_Tolerating_Feelings",
    item %in% c("SOCS_S_5", "SOCS_S_10", "SOCS_S_15", "SOCS_S_20") ~ "SOCS_S_Acting_To_Alleviate"
  ))

sample_n(socs_s_df, 10)

```

```{r}
socs_s_df %>% 
  write_feather("../results/socs_s_tidy.feather")
```

## CEAS-TO

```{r}
ceas_to_df <- filtered_german_df %>%
  select(ResponseId, starts_with("CEAS_TO")) %>% 
  mutate(across(starts_with("CEAS"), as.numeric)) %>% 
  pivot_longer(-ResponseId, names_to = "item", values_to = "response") %>% 
  filter(item != "CEAS_TO1_4") %>% 
  mutate(item_number = if_else(as.numeric(str_extract(item, "\\d+$")) > 4 & str_detect(item, "CEAS_TO1"), as.numeric(str_extract(item, "\\d+$")) - 1, as.numeric(str_extract(item, "\\d+$")))) %>% 
  mutate(item = if_else(str_detect(item, "CEAS_TO1"), str_c("CEAS_TO1_", item_number), item)) %>% 
  select(-item_number) %>%
  group_by(ResponseId) %>%
  filter(!any(is.na(response))) %>%
  ungroup()
```

```{r}
ceas_to_df %>% 
  write_feather("../results/ceas_to_tidy.feather")
```

## CEAS-SC

```{r}
ceas_sc_df <- filtered_german_df %>%
  select(ResponseId, starts_with("CEAS_SC")) %>% 
  mutate(across(starts_with("CEAS"), as.numeric)) %>% 
  pivot_longer(-ResponseId, names_to = "item", values_to = "response") %>% 
  group_by(ResponseId) %>%
  filter(!any(is.na(response))) %>%
  ungroup()
```

```{r}
ceas_sc_df %>% 
  write_feather("../results/ceas_sc_tidy.feather")
```

## CEAS-FROM

```{r}
ceas_from_df <- filtered_german_df %>%
  select(ResponseId, starts_with("CEAS_FROM")) %>% 
  mutate(across(starts_with("CEAS"), as.numeric)) %>% 
  pivot_longer(-ResponseId, names_to = "item", values_to = "response") %>% 
  group_by(ResponseId) %>%
  filter(!any(is.na(response))) %>%
  ungroup()
```

```{r}
ceas_from_df %>% 
  write_feather("../results/ceas_from_tidy.feather")
```

## Ceiling/Floor Effects

```{r}
calculate_ceiling_floor_effects <- function(df, min_value, max_value) {
  min_maxed <- df %>% 
    group_by(ResponseId) %>% 
    summarise(total_score = sum(response)) %>% 
    filter(total_score %in% c(min_value, max_value)) %>% 
    count() %>% 
    pull()
  
  total <- df %>% 
    count(ResponseId) %>% 
    count() %>% 
    pull()
  
  min_maxed / total
}

```

```{r}
calculate_ceiling_floor_effects(socs_o_df, 20, 100)
```

```{r}
dfs <- list(socs_o_df, socs_s_df, ceas_from_df, ceas_sc_df, ceas_to_df)
mins <- list(20, 20, 10, 10, 10)
maxes <- list(100, 100, 100, 100, 100)

pmap(list(dfs, mins, maxes), calculate_ceiling_floor_effects)
```

## Session Information

```{r}
sessionInfo()
```
