---
title: "Online German"
output:
  pdf_document: default
  html_document: default
date: '2022-06-25'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(haven)
library(tidyverse)
library(feather)
library(psych)
library(ggcorrplot)
library(viridis)
library(jtools)
library(lavaan)
library(broom)
library(huxtable)
```

```{r}
german_df <- read_sav("../data/Compassion-DE_24 June 2022_23.31.sav")
```

```{r}
german_df
```

```{r}
filtered_german_df <- german_df %>% 
  filter(SOCS_O_10 == 4) %>% 
  filter(CEAS_TO1_4 == 10)

filtered_german_df
```

```{r}
subscale_german_df <- filtered_german_df %>% 
  select(ResponseId, starts_with("SOCS")) %>% 
  pivot_longer(-ResponseId, names_to = "item", values_to = "response") %>% 
  filter(item != "SOCS_O_10") %>% 
  mutate(item_number = if_else(as.numeric(str_extract(item, "\\d+")) > 10 & str_detect(item, "SOCS_O"), as.numeric(str_extract(item, "\\d+")) - 1, as.numeric(str_extract(item, "\\d+")))) %>% 
  mutate(item = if_else(str_detect(item, "SOCS_O"), str_c("SOCS-O_", item_number), item)) %>% 
  select(-item_number) %>% 
  mutate(item = str_replace(item, "-", "_")) %>% 
  mutate(sub_scale = case_when(
    item %in% c("SOCS_S_1", "SOCS_S_6", "SOCS_S_11", "SOCS_S_16") ~ "SOCS_S_Recognizing_Suffering",
    item %in% c("SOCS_S_2", "SOCS_S_7", "SOCS_S_12", "SOCS_S_17") ~ "SOCS_S_Understanding_Suffering",
    item %in% c("SOCS_S_3", "SOCS_S_8", "SOCS_S_13", "SOCS_S_18") ~ "SOCS_S_Feeling_Suffering",
    item %in% c("SOCS_S_4", "SOCS_S_9", "SOCS_S_14", "SOCS_S_19") ~ "SOCS_S_Tolerating_Feelings",
    item %in% c("SOCS_S_5", "SOCS_S_10", "SOCS_S_15", "SOCS_S_20") ~ "SOCS_S_Acting_To_Alleviate",
    item %in% c("SOCS_O_1", "SOCS_O_6", "SOCS_O_11", "SOCS_O_16") ~ "SOCS_O_Recognizing_Suffering",
    item %in% c("SOCS_O_2", "SOCS_O_7", "SOCS_O_12", "SOCS_O_17") ~ "SOCS_O_Understanding_Suffering",
    item %in% c("SOCS_O_3", "SOCS_O_8", "SOCS_O_13", "SOCS_O_18") ~ "SOCS_O_Feeling_Suffering",
    item %in% c("SOCS_O_4", "SOCS_O_9", "SOCS_O_14", "SOCS_O_19") ~ "SOCS_O_Tolerating_Feelings",
    item %in% c("SOCS_O_5", "SOCS_O_10", "SOCS_O_15", "SOCS_O_20") ~ "SOCS_O_Acting_To_Alleviate"
  ))
```

```{r}
subscale_german_df %>% 
  write_feather("../results/socs_responses.feather")
```

## SOCS-O

```{r}
socs_o_wide <- subscale_german_df %>% 
  filter(str_detect(item, "SOCS_O")) %>% 
  mutate(response = as.numeric(response)) %>%
  pivot_wider(values_from = response, id_cols = ResponseId, names_from = item) %>% 
  filter_all(all_vars(!is.na(.))) %>% 
  select(-ResponseId)

socs_o_wide
```

```{r}
describe(socs_o_wide)
```

```{r}
socs_o_cor <- polychoric(socs_o_wide)
socs_o_cor
```

```{r}
ggcorrplot(socs_o_cor$rho, ggtheme=theme_apa()) +
  scale_fill_viridis()
```

```{r}
eigen(socs_o_cor$rho)$values
```

```{r}
one_factor_model <- str_c("compassion =~ ", str_c(colnames(socs_o_wide), collapse = " + "))
one_factor_model
```

```{r}
one_factor_cfa <- cfa(
  one_factor_model, 
  data=socs_o_wide, 
  estimator="MLR"
  )
one_factor_cfa
```

```{r}
one_factor_glance <- glance(one_factor_cfa)
one_factor_glance
```

```{r}
five_factor_model <- '
recognizing_suffering =~ SOCS_O_1 + SOCS_O_6 + SOCS_O_11 + SOCS_O_16
universality_of_suffering =~ SOCS_O_2 + SOCS_O_7 + SOCS_O_12 + SOCS_O_17
feeling_of_suffering =~ SOCS_O_3 + SOCS_O_8 + SOCS_O_13 + SOCS_O_18
tolerating_discomfort =~ SOCS_O_4 + SOCS_O_9 + SOCS_O_14 + SOCS_O_19
alleviate_suffering =~ SOCS_O_5 + SOCS_O_10 + SOCS_O_15 + SOCS_O_20'
```

```{r}
five_factor_cfa <- cfa(
  five_factor_model, 
  data=socs_o_wide, 
  estimator="MLR"
  )
five_factor_cfa
```

```{r}
socs_o_fit_measures <- fitmeasures(
  five_factor_cfa, 
  fit.measures = c("chisq", "pvalue", "df", "rmsea", "rmsea.ci.lower", "rmsea.ci.upper", "cfi", "tli"))
socs_o_fit_measures[["alpha"]] <- socs_o_alpha

socs_o_fit_measures
```

```{r}
five_factor_glance <- glance(five_factor_cfa)
five_factor_glance
```

```{r}
hierarchical_factor_model <- '
recognizing_suffering =~ SOCS_O_1 + SOCS_O_6 + SOCS_O_11 + SOCS_O_16
universality_of_suffering =~ SOCS_O_2 + SOCS_O_7 + SOCS_O_12 + SOCS_O_17
feeling_of_suffering =~ SOCS_O_3 + SOCS_O_8 + SOCS_O_13 + SOCS_O_18
tolerating_discomfort =~ SOCS_O_4 + SOCS_O_9 + SOCS_O_14 + SOCS_O_19
alleviate_suffering =~ SOCS_O_5 + SOCS_O_10 + SOCS_O_15 + SOCS_O_20
compassion =~ recognizing_suffering + universality_of_suffering + feeling_of_suffering + tolerating_discomfort + alleviate_suffering
'
```

```{r}
hierarchical_factor_cfa <- cfa(
  hierarchical_factor_model, 
  data=socs_o_wide, 
  estimator="MLR"
  )
hierarchical_factor_cfa
```
```{r}
hierarchical_factor_glance <- glance(hierarchical_factor_cfa)
hierarchical_factor_glance
```

```{r}
socs_o_fits <- bind_rows(
  one_factor_glance,
  five_factor_glance,
  hierarchical_factor_glance
)
```

```{r}
socs_o_alpha <- alpha(socs_o_wide)$total$raw_alpha
socs_o_alpha
```


## SOCS-S

```{r}
socs_s_wide <- subscale_german_df %>% 
  filter(str_detect(item, "SOCS_S")) %>% 
  mutate(response = as.numeric(response)) %>%
  pivot_wider(values_from = response, id_cols = ResponseId, names_from = item) %>% 
  filter_all(all_vars(!is.na(.))) %>% 
  select(-ResponseId)

socs_s_wide
```

```{r}
describe(socs_s_wide)
```

```{r}
socs_s_cor <- polychoric(socs_s_wide)
socs_s_cor
```

```{r}
ggcorrplot(socs_s_cor$rho, ggtheme=theme_apa()) +
  scale_fill_viridis()
```

```{r}
eigen(socs_s_cor$rho)$values
```

```{r}
one_factor_model <- str_c("compassion =~ ", str_c(colnames(socs_s_wide), collapse = " + "))
one_factor_model
```

```{r}
one_factor_cfa <- cfa(
  one_factor_model, 
  data=socs_s_wide, 
  estimator="MLR"
  )
one_factor_cfa
```

```{r}
one_factor_glance <- glance(one_factor_cfa)
one_factor_glance
```

```{r}
five_factor_model <- '
recognizing_suffering =~ SOCS_S_1 + SOCS_S_6 + SOCS_S_11 + SOCS_S_16
universality_of_suffering =~ SOCS_S_2 + SOCS_S_7 + SOCS_S_12 + SOCS_S_17
feeling_of_suffering =~ SOCS_S_3 + SOCS_S_8 + SOCS_S_13 + SOCS_S_18
tolerating_discomfort =~ SOCS_S_4 + SOCS_S_9 + SOCS_S_14 + SOCS_S_19
alleviate_suffering =~ SOCS_S_5 + SOCS_S_10 + SOCS_S_15 + SOCS_S_20'
```

```{r}
five_factor_cfa <- cfa(
  five_factor_model, 
  data=socs_s_wide, 
  estimator="MLR"
  )
five_factor_cfa
```

```{r}
five_factor_glance <- glance(five_factor_cfa)
five_factor_glance
```

```{r}
socs_s_fit_measures <- fitmeasures(
  five_factor_cfa, 
  fit.measures = c("chisq", "pvalue", "df", "rmsea", "rmsea.ci.lower", "rmsea.ci.upper", "cfi", "tli"))
socs_s_fit_measures[["alpha"]] <- socs_s_alpha
```

```{r}
socs_s_fit_measures
```

```{r}
fitmeasures(
  five_factor_cfa)
```


```{r}
hierarchical_factor_model <- '
recognizing_suffering =~ SOCS_S_1 + SOCS_S_6 + SOCS_S_11 + SOCS_S_16
universality_of_suffering =~ SOCS_S_2 + SOCS_S_7 + SOCS_S_12 + SOCS_S_17
feeling_of_suffering =~ SOCS_S_3 + SOCS_S_8 + SOCS_S_13 + SOCS_S_18
tolerating_discomfort =~ SOCS_S_4 + SOCS_S_9 + SOCS_S_14 + SOCS_S_19
alleviate_suffering =~ SOCS_S_5 + SOCS_S_10 + SOCS_S_15 + SOCS_S_20
compassion =~ recognizing_suffering + universality_of_suffering + feeling_of_suffering + tolerating_discomfort + alleviate_suffering
'
```

```{r}
hierarchical_factor_cfa <- cfa(
  hierarchical_factor_model, 
  data=socs_s_wide, 
  estimator="MLR"
  )
hierarchical_factor_cfa
```
```{r}
hierarchical_factor_fit <- fitmeasures(hierarchical_factor_cfa)
hierarchical_factor_fit["pvalue"]
```



```{r}
hierarchical_factor_glance <- glance(hierarchical_factor_cfa)
hierarchical_factor_glance
```

```{r}
socs_s_fits <- bind_rows(
  one_factor_glance,
  five_factor_glance,
  hierarchical_factor_glance
)
```

```{r}
socs_s_alpha <- alpha(socs_s_wide)$total$raw_alpha
socs_s_alpha
```


```{r}
model_names <- c("One Factor", "Five Factor", "Hierarchical")
socs_s_fits %>% 
  bind_cols(model_name = model_names) %>% 
  select()
```
## Constructing Figure

```{r}
bind_rows(socs_o_fit_measures, socs_s_fit_measures) %>% 
  transmute(
    Scale = c("SOCS-O", "SOCS-S"), 
    α = round(alpha, 2),
    Model = "5 > 1, second order",
    `χ²` = str_c(round(chisq, 2), " (p < 0.001)"),
    Df = df,
    `RMSEA [90% C.I.]` = str_c(round(rmsea, 2), " [", round(rmsea.ci.lower, 2), ", ", round(rmsea.ci.upper, 2), "]"),
    CFI = round(cfi, 2),
    TLI = round(tli, 2),
    ) %>% 
  as_huxtable() %>% 
  theme_grey() %>% 
  quick_docx()
```






```{r}
sessionInfo()
```

